openapi: 3.0.1
info:
  title: Haul Patrol API
  description: Schema describing how Haul Patrol accepts quote and contact requests.
  version: "1.0.0"
servers:
  - url: https://haulpatrol.com
paths:
  /contact:
    post:
      summary: Submit a junk removal quote request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                message:
                  type: string
      responses:
        "200":
          description: Submission received successfully
components:
  securitySchemes: {}
